OctopusDeploy/Nevermore

- source/Nevermore.IntegrationTests/RelationalStoreFixture.cs
- source/Nevermore.Tests/Nevermore.Tests.xproj
- source/Nevermore.Tests/RelationalStoreFixture.cs
- source/Nevermore/RelationalStore.cs
Relates to OctopusDeploy/Issues#3035
> Do not override values specified in connection string

- source/Nevermore.Tests/QueryBuilderFixture/VariableCasingFixture.cs
- source/Nevermore/SqlQueryGenerator.cs
Relates to OctopusDeploy/Issues#3331
> Lower case params for WHERE IN

- source/Nevermore.IntegrationTests/FixtureWithRelationalStore.cs
- source/Nevermore.IntegrationTests/IntegrationTestDatabase.cs
- source/Nevermore.IntegrationTests/RelationalStoreFixture.cs
- source/Nevermore/RelationalTransaction.cs
Relates to https://github.com/OctopusDeploy/OctopusDeploy/pull/1054
> Support case sensitive database collation

- source/Nevermore.Tests/Mapping/AmazingConverterFixture.cs
- source/Nevermore.Tests/Nevermore.Tests.csproj
This test was previous a part of the `Octopus.Shared` tests in `OctopusDeploy`.
> Add test for AmazingConverter

- source/Nevermore/DeleteQueryBuilder.cs
- source/Nevermore/IDeleteQueryBuilder.cs
- source/Nevermore/IRelationalTransaction.cs
- source/Nevermore/RelationalTransaction.cs
Added IId contraint to the Delete and DeleteById methods on the IRelationalTransaction interface.
Added AsType method to IDeleteQueryBuilder.
> Constrain deletes to IId

- source/Nevermore.Contracts/ReferenceCollection.cs
Small improvement to performance, using the dedicated ctors on the Hashtable makes a bit of a difference
> Use HashSet ctor overloads

- source/Nevermore.Tests/Linq/LinqWhereClauseMethodOperationTests.cs
- source/Nevermore/QueryBuilderWhereExtensions.cs
https://github.com/OctopusDeploy/Issues/issues/5266
> Fixed bug when doing a `Contains` expression on a string list

- source/Nevermore/RelationalTransaction.cs
Relates to OctopusDeploy/Issues#5325
> Allow instance instantiation with private constructor

- source/Nevermore/UpgradeScripts/Script0001-KeyAllocation.sql
> Fixed inconsistent casing

- build.cake
- source/Nevermore.IntegrationTests/Nevermore.IntegrationTests.csproj
- source/Nevermore.Tests/Nevermore.Tests.csproj
- source/Nevermore/Diagnostics/DefaultQueryLogger.cs
- source/Nevermore/Diagnostics/IQueryLogger.cs
- source/Nevermore/Diagnostics/TimedSection.cs
- source/Nevermore/RelationalStore.cs
- source/Nevermore/RelationalTransaction.cs
This is based off the previous version of Nevermore (v11). A bit of work will be needed to integrate with v12.
This changes enables https://github.com/OctopusDeploy/OctopusDeploy/pull/6125/commits/3844193ae80358a3ce56540adfa9914aace82bb5#diff-ee9d169a91384cdb99f41f483c248d84R6 for Telemetry
> Added `IQueryLogger` which gives the ability to hook in telemetry

- build.cake
- source/Nevermore.Extensions.DependencyInjection/Nevermore.Extensions.DependencyInjection.csproj
- source/Nevermore.Extensions.DependencyInjection/NevermoreServiceCollectionExtensions.cs
- source/Nevermore.sln
This adds `AddNevermore` extensions methods on `IServiceCollection`.
> Add Nevermore.Extensions.DependencyInjection

- source/Nevermore/Nevermore.csproj
Get the fix for https://github.com/dotnet/SqlClient/issues/374
This will also allow [Azure Managed Service Identity](https://github.com/OctopusDeploy/OctopusAdvisoryTeam/issues/21)
> Update SqlClient to 2.1.1

- build.ps1
- build.sh
This is probably security relevant
> Fix package.config URL

- source/Nevermore.Analyzers.Tests/NevermoreWhereExpressionAnalyzerFixture.cs
- source/Nevermore.Analyzers/NevermoreWhereExpressionAnalyzer.cs
- source/Nevermore.Analyzers/NevermoreWhereExpressionVisitor.cs
> Analyzer now understands the null-forgiving operator.

- source/Nevermore.Analyzers.Tests/CodeCompiler.cs
- source/Nevermore.Analyzers.Tests/NevermoreWhereExpressionAnalyzerFixture.cs
- source/Nevermore.Analyzers/NevermoreWhereExpressionAnalyzer.cs
> Check is bypassed if a variable is passed into the Where clause

- source/Nevermore/Advanced/RelationalTransactionRegistry.cs
As part of some performance analysis done in Octopus Server, I noticed that once the concurrency story increases this lock has a significant impact on performance.
This PR replaces the List/lock with a ConcurrentDictionary
> Remove lock from RelationalTransactionRegistry

- source/Nevermore/Nevermore.csproj
Get the fix for https://github.com/dotnet/SqlClient/issues/839
> SqlClient minor version bump

- source/Nevermore.Analyzers.Tests/Nevermore.Analyzers.Tests.csproj
- source/Nevermore.IntegrationTests/Advanced/RowVersionFixture .cs
- source/Nevermore.IntegrationTests/Nevermore.IntegrationTests.csproj
- source/Nevermore.IntegrationTests/RelationalStoreFixture.cs
- source/Nevermore.IntegrationTests/RelationalTransaction/DeleteFixture.cs
- source/Nevermore.IntegrationTests/RelationalTransaction/LoadFixture.cs
- source/Nevermore.Tests/Column/ColumnExpressionTests.cs
- source/Nevermore.Tests/Delete/DeleteQueryBuilderFixture.cs
- source/Nevermore.Tests/Nevermore.Tests.csproj
- source/Nevermore.Tests/QueryBuilderFixture/QueryBuilderFixture.cs
- source/Nevermore.Tests/QueryBuilderFixture/QueryBuilderStateFixture.cs
Updating because I need a new feature in it
> Updated FluentAssertions to the latest version

- source/Nevermore.IntegrationTests/Advanced/IdentityIdFixture.cs
- source/Nevermore.IntegrationTests/KeyAllocatorFixture.cs
- source/Nevermore/Advanced/ReadTransaction.cs
- source/Nevermore/Mapping/KeyAllocator.cs
One day we want transaction names to be mandatory. This PR gets us one step closer, at least on this repository.
> Added transaction names

- .gitattributes
It was identified that line-handling is causing issue with the SQL migration scripts
> Add missing line-handling attribute

- source/Nevermore/Nevermore.csproj
https://github.com/dependency-insights/nuget/Newtonsoft.Json/12.0.3/security?query=org%3AOctopusDeploy
> Patch Newtonsoft JSON vulnerability

- source/Nevermore.Benchmarks/Nevermore.Benchmarks.csproj
- source/Nevermore.IntegrationTests/Nevermore.IntegrationTests.csproj
- source/Nevermore.IntegrationTests/SetUp/DatabaseMigrator.cs
> Updated DbUp to fix the SqlClient vulnerability

- source/Nevermore.IntegrationTests/Advanced/RelationalTransactionRegistryFixture.cs
A recent change made pooled connect timeouts a retriable error. An unintended consequence of this is now the test run takes a lot longer. This is due to the `RelationalTransactionRegristryFixture`, which deliberately exhausts the connection pool to validate some functionality. The test still works as intended, it just takes significantly longer now due to the retries being done.
Disable retries for the affected fixture. Configuring retries is done in global state, so it's possible this _may_ affect other test fixtures too. Ideally, retries would be part of the relational store configuration, but that's a problem for another day.
Test suite runtime: ~10 minutes
Test suite runtime: ~4.5 minutes
> Speed up tests

- source/Nevermore.Tests/QueryBuilderFixture/QueryBuilderFixture.cs
- source/Nevermore/Advanced/QueryBuilder.cs
- source/Nevermore/Advanced/QueryBuilders/JoinSourceQueryBuilder.cs
- source/Nevermore/Advanced/QueryBuilders/SourceQueryBuilder.cs
- source/Nevermore/Advanced/QueryBuilders/SubquerySourceBuilder.cs
- source/Nevermore/Advanced/QueryBuilders/TableSourceQueryBuilder.cs
- source/Nevermore/Advanced/QueryBuilders/UnionSourceBuilder.cs
- source/Nevermore/IQueryBuilder.cs
- source/Nevermore/QueryBuilderJoinExtensions.cs
> Added lhs query alias for joins

- source/Nevermore/Advanced/RelationalTransactionRegistry.cs
The `RelationalTransactionRegistry` is responsible for logging warnings when a high number of active transactions is detected.
If the number of transactions reaches 90% of the maximum pool size or exceeds the maximum size, a comprehensive list of transactions is logged. This check happens when adding another transaction to the registry.
Currently, there's a `highNumberAlreadyLoggedAtError` flag that determines whether this list should be logged. The flag is set to true after the first log, preventing subsequent logs.
This PR replaces the flag with a `DateTime` and refactors the logic to log the list of transactions every minute if the high transaction count condition is met.
> Log transactions every minute (when there are a high number active)

- build.ps1
- build.sh
- build/Build.cs
- build/_build.csproj
- global.json
- source/Nevermore.Analyzers.Tests/Nevermore.Analyzers.Tests.csproj
- source/Nevermore.Benchmarks/Nevermore.Benchmarks.csproj
- source/Nevermore.IntegrationTests/Nevermore.IntegrationTests.csproj
- source/Nevermore.Tests/Nevermore.Tests.csproj
[sc-65325]
Upgrades this repo to use the .NET 8 SDK.
> Use .NET 8 SDK
