- source/Nevermore/IRelationalStore.cs
- source/Nevermore/RelationalStore.cs
- source/Nevermore/RelationalTransactionRegistry.cs
This will allow us to limit `ClusterWideMutex` to 20% of the SQL Connection Pool (for example)
> Forward MaxPoolSize for use in Octopus Server.

- source/Nevermore.IntegrationTests/Chaos/ChaosSqlCommandFactory.cs
- source/Nevermore.IntegrationTests/Nevermore.IntegrationTests.xproj
- source/Nevermore/IRelationalTransaction.cs
- source/Nevermore/ISqlCommandFactory.cs
- source/Nevermore/RelationalTransaction.cs
- source/Nevermore/SqlCommandFactory.cs
The reason I'm considering this is so `ClusterWideMutex` can provide a custom (shorter) command timeout. The default of 60s doesn't provide a very good feedback cycle. This probably won't matter for many situations, but the `ClusterWideMutex` is a very special case where we expect other processes to lock on that exact record, and some of those processes could be long-running.
What would also be lovely is if we could provide cooperative cancellation support... this gets a bit harder because we'd need to use `CancellationToken.Register` and then dispose of the returned `CancellationTokenRegistration` once the `IDbCommand` has completed. This would require a signature and slight behaviour change of the `ISqlCommandFactory`.
> Provide ability to set a non-default command timeout

- source/Nevermore/RelationalTransaction.cs
- source/Nevermore/RelationalTransactionRegistry.cs
- source/Nevermore/Transient/SqlDatabaseTransientErrorDetectionStrategy.cs
Profiling shows a high JIT cost to creating a new typed-ILog instance per dependency. The logging framework itself is thread-safe so we should just use a static typed-ILog instance.
> Use a static ILog instance for perf

- source/Nevermore.Contracts/Nevermore.Contracts.csproj
1.5 was causing issues with referencing the package in ODCM
> Roll contracts dependency back to netstandard1.2

- source/Nevermore.Tests/QueryBuilderFixture/QueryBuilderFixture.cs
- source/Nevermore/SqlQueryGenerator.cs
IN queries will add parameter names with spaces  eg `@foo 1` which will break the query.  This normalizes spaces in parameter names.
> Normalize spaces in parameter names

- source/Nevermore.Tests/QueryBuilderFixture/QueryBuilderFixture.cs
- source/Nevermore/SqlQueryGenerator.cs
Using parameter values as the parameter name when doing "IN" clauses is fraught with danger.  Instead, let's use the parameter name.
Relates to OctopusDeploy/Issues#3607
> Use parameter name instead of value for IN clauses

- source/Nevermore/RelationalTransaction.cs
Update and Insert were recently broken because the InstanceToParameters was changed to add the parameter `@JSON` but the SQL statement was still referring to `@Json`. This works fine when the Server Collation of the SQL Server is CI, but breaks when the Server Collation is CS (regardless of the Database Collation). See the related issue for more details.
I've got more work in progress to protect ourselves from some other problems that exist over in Octopus since these changes:
- Some mappings accidentally included the `Json` column causing https://github.com/OctopusDeploy/Issues/issues/3733
Fixes https://github.com/OctopusDeploy/Issues/issues/3734
> Fixed the casing of @Json parameter

- source/Nevermore.Contracts/ReferenceCollection.cs
- source/Nevermore/Mapping/ColumnMapping.cs
- source/Nevermore/Mapping/DatabaseTypeConverter.cs
- source/Nevermore/Mapping/ReferenceCollectionReaderWriter.cs
This change was originally slated for the ODCM changes, but we're aiming to release the user changes in 3.X
Update is primarily so Octopus.Data can use ReferenceCollection in IUser.
> Moved ReferenceCollection to Nevermore.Contracts

- source/Nevermore.IntegrationTests/IntegrationTestDatabase.cs
- source/Nevermore.IntegrationTests/Model/ProductMap.cs
- source/Nevermore.IntegrationTests/RelationalStoreFixture.cs
- source/Nevermore/Mapping/SubTypedResolver.cs
- source/Nevermore/RelationalTransaction.cs
Means that subtype mappings can pull from different columns as well as JSON, so allowing document hierarchies that pull from different bits of the table as well as different bits of JSON.
> allow subclasses from column data, as well as JSON

- source/Nevermore.Tests/QueryBuilderFixture/QueryBuilderFixture.ShouldGenerateSelectForMultipleJoinsWithParameter.approved.txt
- source/Nevermore.Tests/QueryBuilderFixture/QueryBuilderFixture.ShouldGenerateWithMultipleLeftHashJoinsSubQueryWithPrameter.approved.txt
- source/Nevermore.Tests/QueryBuilderFixture/QueryBuilderFixture.ShouldGenerateWithMultipleLeftHashJoinsWithTableAndSubQueryWithPrameter.approved.txt
- source/Nevermore.Tests/QueryBuilderFixture/QueryBuilderFixture.cs
- source/Nevermore/QueryBuilderJoinExtensions.cs
- source/Nevermore/SourceQueryBuilder.cs
- Parameters from the subsequence `InnerJoin` source are ignored if a query has more than 1 `InnerJoin` clauses
- `LeftHashJoin` pass the same parameters from itself rather than from the right hand side query
- Add the parameters into the query builder from the right hand side query
LeftHashJoin in the version prior this PR took `IAliasedSelectSource` as the right hand side for join. In this case we lose the ability to pass its parameters to form a new `IQueryBuilder`, thought that sometimes we might not have any parameter. As we updated the `JoinSourceQueryBuilder` in solution 1, it accidentally trigger a bug where `LeftHashJoin` pass the parameters from itself to form a new `IQueryBuilder`. So using `IAliasedSelectSource` is very error prone as it only works if the left hand side query …
> Fix a couple problems when using InnerJoin and LeftHashJoin

- source/Nevermore.IntegrationTests/RelatedDocumentTableFixture.cs
- source/Nevermore.IntegrationTests/SchemaGenerator.cs
- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.DeleteByDocument.approved.txt
- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.DeleteByDocumentWithManyRelatedTables.approved.txt
- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.DeleteByDocumentWithOneRelatedTable.approved.txt
- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.DeleteById.approved.txt
- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.DeleteByWhere.approved.txt
- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.InsertMultipleDocumentWithManyRelatedDocuments.approved.txt
- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.InsertMultipleDocumentWithMultipleRelatedDocumentsMaps.approved.txt
- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.InsertMultipleDocuments.approved.txt
- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.InsertSingleDocument.approved.txt
- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.InsertSingleDocumentWithDocumentIdAlreadySet.approved.txt
- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.InsertSingleDocumentWithManyRelatedDocuments.approved.txt
- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.InsertSingleDocumentWithNoRelatedDocuments.approved.txt
- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.InsertSingleDocumentWithOneRelatedDocument.approved.txt
- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.InsertWithoutDefaultColumns.approved.txt
- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.Update.approved.txt
- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.UpdateWithHint.approved.txt
- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.UpdateWithManyRelatedDocuments.approved.txt
- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.UpdateWithNoRelatedDocuments.approved.txt
- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.UpdateWithOneRelatedDocument.approved.txt
- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.cs
- source/Nevermore/IRelationalStore.cs
- source/Nevermore/Mapping/RelatedDocumentsMapping.cs
- source/Nevermore/RelationalStore.cs
- source/Nevermore/Util/DataModificationQueryBuilder.cs
A previous change changed the `IdTypeColumnName` to store the table name instead of the type and I didn't rename the column correctly at that time, which was misleading. After implementing in Octopus, it turns out determining the real `RelatedDocumentType` is tricky and not really required, just storing the table name is sufficient.
> Store the table name instead of the document type

- source/Nevermore.IntegrationTests/IntegrationTestDatabase.cs
- source/Nevermore.IntegrationTests/Model/Brand.cs
- source/Nevermore.IntegrationTests/Model/BrandMap.cs
- source/Nevermore.IntegrationTests/Model/CustomerMap.cs
- source/Nevermore.IntegrationTests/Model/Machine.cs
- source/Nevermore.IntegrationTests/Model/MachineMap.cs
- source/Nevermore.IntegrationTests/Model/ProductMap.cs
- source/Nevermore.IntegrationTests/RelationalTransaction/LoadFixture.cs
- source/Nevermore/Mapping/DocumentMap.cs
- source/Nevermore/Mapping/InstanceTypeResolver.cs
- source/Nevermore/Mapping/RelationalMappings.cs
- source/Nevermore/Mapping/StandardTypeResolver.cs
- source/Nevermore/Mapping/SubTypedResolver.cs
- source/Nevermore/RelationalTransaction.cs
- source/Nevermore/Serialization/InheritedClassConverter.cs
- source/Nevermore/Serialization/InheritedClassConverterBase.cs
We can now support using a JSON converter to handle subtyping the same way we do in the API. This means the type namespaces won't be serialized into the DB and we are not going to break if we move types to different namespaces/assemblies.
Added tests to ensure the serialization is correct, and to guard against it accidentally changing in the future.
> Change subtype handling

- source/Nevermore/Nevermore.csproj
- source/Nevermore/ObjectInitialisationOptions.cs
- source/Nevermore/RelationalStore.cs
- source/Nevermore/RelationalTransaction.cs
Instead of always using non-public constructors, pass a flag that will determine if non-public constructors can be used.  This maintains backwards compatability.
> Use flag for object init to preserve backwards compat

- source/Nevermore.IntegrationTests/IntegrationTestDatabase.cs
- source/Nevermore.IntegrationTests/Model/CustomerMap.cs
- source/Nevermore.IntegrationTests/QueryBuilderIntegrationFixture.cs
- source/Nevermore.IntegrationTests/RelationalTransaction/LoadFixture.cs
- source/Nevermore.Tests/Linq/LinqWhereClauseComparisonTypeTests.cs
- source/Nevermore/AST/Where.cs
- source/Nevermore/IQueryBuilder.cs
- source/Nevermore/ISelectBuilder.cs
- source/Nevermore/IsNullWhereParameter.cs
- source/Nevermore/QueryBuilder.cs
- source/Nevermore/QueryBuilderWhereExtensions.cs
- source/Nevermore/SelectBuilder.cs
- source/Nevermore/SourceQueryBuilder.cs
Added ability to compare to null in where expressions
e.g. `t.TableQuery<Customer>().Where(c => c.Nickname == null)`
>  Ability to compare to null in where expressions

- source/Nevermore.IntegrationTests/IntegrationTestDatabase.cs
- source/Nevermore.IntegrationTests/Model/Customer.cs
- source/Nevermore.IntegrationTests/Model/CustomerMap.cs
- source/Nevermore.IntegrationTests/RelationalStoreFixture.cs
- source/Nevermore.IntegrationTests/SchemaGenerator.cs
- source/Nevermore.Tests/Nevermore.Tests.csproj
- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.InsertDocumentWithReadOnlyColumn.approved.txt
- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.InsertMultipleDocumentWithManyRelatedDocuments.approved.txt
- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.InsertMultipleDocumentWithMultipleRelatedDocumentsMaps.approved.txt
- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.InsertMultipleDocuments.approved.txt
- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.InsertSingleDocument.approved.txt
- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.InsertSingleDocumentWithDocumentIdAlreadySet.approved.txt
- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.InsertSingleDocumentWithManyRelatedDocuments.approved.txt
- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.InsertSingleDocumentWithOneRelatedDocument.approved.txt
- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.InsertSingleDocumentWithTableNameAndHints.approved.txt
- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.InsertWithoutDefaultColumns.approved.txt
- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.Update.approved.txt
- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.UpdateWithHint.approved.txt
- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.UpdateWithManyRelatedDocuments.approved.txt
- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.UpdateWithNoRelatedDocuments.approved.txt
- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.UpdateWithOneRelatedDocument.approved.txt
- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.cs
- source/Nevermore/Mapping/ColumnMapping.cs
- source/Nevermore/Mapping/DocumentMap.cs
- source/Nevermore/Util/DataModificationQueryBuilder.cs
For some columns, the database itself calculates values, and Nevermore should be able to be configured to read a column but not include in insert/update statements. RowVersion and SQL Calculated Columns are examples of this. 
For example, in a derived class of  `DocumentMap` , this configures the RowVersion column to be read from the database and not updated/inserted:
```
Column(m => m.RowVersion).ReadOnly();
```
> Added ReadOnly option for columns

- source/Nevermore.IntegrationTests/Chaos/ChaosSqlCommandFactory.cs
- source/Nevermore.Tests/Delete/DeleteQueryBuilderFixture.cs
- source/Nevermore/DeleteQueryBuilder.cs
- source/Nevermore/ICompleteQuery.cs
- source/Nevermore/IDeleteQueryBuilder.cs
- source/Nevermore/IQueryBuilder.cs
- source/Nevermore/IQueryExecutor.cs
- source/Nevermore/ISqlCommandFactory.cs
- source/Nevermore/QueryBuilder.cs
- source/Nevermore/RelationalTransaction.cs
- source/Nevermore/SourceQueryBuilder.cs
- source/Nevermore/SqlCommandFactory.cs
Add missing timing log messages for `RelationalTransaction.ExecuteReader()` and `RelationalTransaction.Stream()`
Add missing command timeout options to `IQueryExecutor` methods
Add `IQueryBuilder.WithTimeout()` method which allows you to specify a command timeout when using `IQueryBuilder`.
Fixes: https://github.com/OctopusDeploy/Nevermore/issues/68
> Add more options to specify command timeouts and add missing timing log messages

- source/Nevermore.Tests/Joins/JoinClauseFixture.cs
- source/Nevermore.Tests/QueryBuilderFixture/QueryBuilderFixture.ShouldGenerateSelectForChainedJoins.approved.txt
- source/Nevermore.Tests/QueryBuilderFixture/QueryBuilderFixture.cs
- source/Nevermore/AST/JoinedSource.cs
- source/Nevermore/IQueryBuilder.cs
- source/Nevermore/SourceQueryBuilder.cs
Previously you could only use columns from the primary table when performing a join.
```
SELECT *
FROM Table1
INNER JOIN Table2
ON Table1.Table2Fk = Table2.Pk
INNER JOIN Table3
ON Table1.Table3Fk = Table3.Pk
```
The changes allow you to use a column from any table on the join condition
```
SELECT *
FROM Table1
INNER JOIN Table2 Table2Alias
ON Table1.Table2Fk = Table2.Pk
INNER JOIN Table3
ON Table2Alias.Table3Fk = Table3.Pk
```
By calling:
```
table1
.InnerJoin(table2).On("Table2Fk", JoinOperand.Equal, "Pk")
.InnerJoin(table3).On("Table2Alias", "Table3Fk", JoinOperand.Equal, "Pk")
```
> QueryBuilder supports Join columns that are not on the primary table

- source/Nevermore.Tests/QueryBuilderFixture/QueryBuilderFixture.Replace_LatestSuccessfulDeployments.approved.txt
- source/Nevermore.Tests/QueryBuilderFixture/QueryBuilderFixture.Replace_Release_LatestByProjectChannel.approved.txt
- source/Nevermore.Tests/QueryBuilderFixture/QueryBuilderFixture.cs
- source/Nevermore/IQueryBuilder.cs
- source/Nevermore/ISelectBuilder.cs
- source/Nevermore/QueryBuilder.cs
- source/Nevermore/SelectBuilder.cs
- source/Nevermore/SourceQueryBuilder.cs
To minimize the number of subqueries required to generate what's required by `Replace_LatestSuccessfulDeployments` the orderby column requires alias support so it can be selected from another table in the query
> Order by with table alias

- source/Nevermore.Tests/QueryBuilderFixture/QueryBuilderFixture.cs
- source/Nevermore.Tests/QueryBuilderFixture/QueryBuilderStateFixture.cs
- source/Nevermore/ICompleteQuery.cs
- source/Nevermore/QueryBuilder.cs
- source/Nevermore/RelationalTransaction.cs
- source/Nevermore/SourceQueryBuilder.cs
`ICompleteQuery.First` currently returns `null` if the result of the query returns no records. In contrast, the commonly used `Enumerable.First` method never returns null, and the behavior of `ICompleteQuery.First` more closely mirrors that of `Enumerable.FirstOrDefault`. This inconsistency has [caused some confusion](https://github.com/OctopusDeploy/Octofront/pull/1093#discussion_r311825078), which gave rise to the suggestion for the following change in Nevermore.
This PR marks the `ICompleteQuery.First` as `Obsolete`, and introduces a new, equivalent method in its place called `ICompleteQuery.FirstOrDefault`, which is more consistent with the naming scheme used by `Enumerable` and is hoped to be less surprising for users.
While this PR will likely initially cause a significant number of …
> Rename `First` (which can return null) to `FirstOrDefault`

- source/Nevermore/Mapping/PropertyReaderFactory.cs
- source/Nevermore/Nevermore.csproj
```
public class Customer : IId
{
public string Id { get; }
}
// ...
transaction.Insert(new Customer());
```
Confusing null ref:
```
System.NullReferenceException: Object reference not set to an instance of an object.
```
A slightly more informative error message that points to the issue (i.e. in this case, that the `Id` has no `set` accessor):
```
System.InvalidOperationException: Cannot write to a property without a setter
```
> Improve error message when a document is missing a setter

- source/Nevermore.Contracts/Nevermore.Contracts.csproj
- source/Nevermore.IntegrationTests/IntegrationTestDatabase.cs
- source/Nevermore.IntegrationTests/Nevermore.IntegrationTests.csproj
- source/Nevermore.Tests/Nevermore.Tests.csproj
- source/Nevermore/AST/JoinedSource.cs
- source/Nevermore/Nevermore.csproj
Enables development on non-windows machines.
Changes include
- Removing .net framework target support. Only target netstandard and netcore
- Add support for supplying a username/password instead of relying on integrated auth in integration tests.
> Improve development experience of Nevermore on Linux

- source/Nevermore/ICompleteQuery.cs
- source/Nevermore/IRelationalStore.cs
- source/Nevermore/QueryBuilder.cs
- source/Nevermore/RelationalStore.cs
- source/Nevermore/SourceQueryBuilder.cs
Nevermore used to force MARS. We need a way to a) disable this behaviour and b) keep the current behaviour in place of existing consumers.
Use
> Added ability to change the default setting for MARS

- source/Nevermore.Tests/CommandParameterValuesFixture.cs
- source/Nevermore/CommandParameterValues.cs
This issue was discovered [here](https://github.com/OctopusDeploy/Issues/issues/6185).
When using a parameter with a list of values, Nevermore will rewrite the query to build an inline list featuring a new parameter for each list item. For example:
```
SELECT * FROM [Table] WHERE [Id] IN @ids
```
becomes:
```
SELECT * FROM [Table] WHERE [Id] IN (@ids_0, @ids_1, ...@ids_n)
```
This uses a Regex to match the name of the parameter to replace, but will also match other identifiers that partially match. For example:
```
SELECT * FROM [Table] WHERE [Id] IN @ids AND [OtherThing] = @ids123
```
becomes:
```
SELECT * FROM [Table] WHERE [Id] IN (@ids_0, @ids_1) AND [OtherThing] = (@ids_0, @ids_1)123
```
which is clearly not valid SQL.
Adjust the Regex match pattern to include a look-ahead for a …
> Ensure list parameter replacement doesn't partially match similar parameter names

- source/Nevermore.IntegrationTests/Contracts/ReferenceCollection.cs
- source/Nevermore.IntegrationTests/Model/Customer.cs
- source/Nevermore/Advanced/ReaderStrategies/Documents/DocumentReaderExpressionBuilder.cs
The `PropertyHandler` had set itself up to handle this case, but `DocumentReaderExpressionBuilder` had a bug where it was still trying to cache an assigner. This threw an exception because the assigner couldn't work without the setter.
Changed the Customer object in the model to expose the issue and prove the fix.
> Fixed bug with collection properties with no setter

- source/Nevermore.IntegrationTests/RelationalStoreFixture.cs
- source/Nevermore/Advanced/ProjectionMapper.cs
There are times where prefixing every column individually in a projection is problematic. Octopus server has cases, for example, where it needs a Release document plus 1 other value from a projected SELECT. In this scenario the columns primarily map to a single document and it is easier to not require a prefix.
This change assumes column names will match the mapped column names if the prefix is null or whitespace.
> Allow a blank prefix when mapping a projection

- source/Nevermore.IntegrationTests/SetUp/FixtureWithRelationalStore.cs
- source/Nevermore.Tests/Delete/DeleteQueryBuilderFixture.cs
- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.cs
- source/Nevermore/Advanced/ReadTransaction.cs
- source/Nevermore/Advanced/WriteTransaction.cs
- source/Nevermore/ConfigurationExtensions.cs
- source/Nevermore/Mapping/DocumentMapRegistry.cs
- source/Nevermore/Mapping/RelatedDocumentsMapping.cs
- source/Nevermore/RelationalStoreConfiguration.cs
- source/Nevermore/Util/DataModificationQueryBuilder.cs
I noticed that when simply setting the default schema name on the configuration like this, it wouldn't work.
```csharp
var config = new RelationalStoreConfiguration(ConnectionString);
config.DefaultSchema = "TestSchema";
```
That's because the configuration was propagated down from `DocumentMapRegistry`, overwriting values on map and related map.
Instead I would vote for leaving schema name on maps as they are, and evaluate actual schema name when building the queries. That way we can use the `DefaultSchema` property on the configuration, and don't need to create a new `DocumentMapRegistry` before adding mappings.
> Fix default schema usage on configuration

- build.cake
- source/Nevermore/Advanced/ReadTransaction.cs
- source/Nevermore/Diagnostics/DefaultQueryLogger.cs
- source/Nevermore/Diagnostics/IQueryLogger.cs
- source/Nevermore/Diagnostics/TimedSection.cs
- source/Nevermore/IRelationalStoreConfiguration.cs
- source/Nevermore/RelationalStoreConfiguration.cs
Brings #108 to Nevermore 12
One notable change is that each Read query will now generate two log entries, the execution of the reader and the read of the result.
> Query Logging for v12

- source/Nevermore.Tests/Column/ColumnExpressionTests.cs
- source/Nevermore.Tests/Linq/LinqTestBase.cs
- source/Nevermore.Tests/QueryBuilderFixture/QueryBuilderFixture.cs
- source/Nevermore.Tests/QueryBuilderFixture/QueryBuilderStateFixture.cs
- source/Nevermore.Tests/QueryBuilderFixture/VariableCasingFixture.cs
- source/Nevermore/Advanced/ReadTransaction.cs
- source/Nevermore/Advanced/SelectBuilder.cs
- source/Nevermore/Advanced/SourceQueryBuilder.cs
- source/Nevermore/CommandParameterValues.cs
This fixes #111 
I didn't change `GetDefaultOrderByFields` in `JoinSelectBuilder`, `UnionSelectBuilder` and `SubquerySelectBuilder` as it seems the order by clause is omitted there.
Could there be cases when `DocumentMap.IdColumn` is `null`? But I figure then it is a wrong document mapping anyway?
> #111 Use Id column mapping for default order by clause

- source/Nevermore.Benchmarks/LoadManyBenchmark.cs
- source/Nevermore.IntegrationTests/Advanced/HooksFixture.cs
- source/Nevermore.IntegrationTests/Model/Message.cs
- source/Nevermore.IntegrationTests/Model/MessageMap.cs
- source/Nevermore.IntegrationTests/RelationalTransaction/LoadFixture.cs
- source/Nevermore.IntegrationTests/SetUp/FixtureWithRelationalStore.cs
- source/Nevermore.IntegrationTests/SetUp/SchemaGenerator.cs
- source/Nevermore/Advanced/Hooks/HookRegistry.cs
- source/Nevermore/Advanced/Hooks/IHook.cs
- source/Nevermore/Advanced/ReadTransaction.cs
- source/Nevermore/Advanced/WriteTransaction.cs
- source/Nevermore/CommandParameterValues.cs
- source/Nevermore/IReadQueryExecutor.cs
- source/Nevermore/IWriteQueryExecutor.cs
- source/Nevermore/InsertOptions.cs
- source/Nevermore/Mapping/DocumentMap.cs
- source/Nevermore/Mapping/DocumentMapRegistry.cs
- source/Nevermore/Mapping/IDocumentMapRegistry.cs
- source/Nevermore/ResourceNotFoundException.cs
- source/Nevermore/Util/DataModificationQueryBuilder.cs
This is an attempt to improve support for non-string ID columns as stated in #113.
Main changes (which need to be discussed):
- Change `Load` signatures to use `object`
- **[breaking]** Seperate `Load` methods which load multiple documents to `LoadMany`. Change signature to `object[]` or `params object[]` because `IEnumerable<object>` doesn't work for any type.
Please let me know if this is something you approve, or if we should solve this another way.
> #113 Improve support for non-string ID columns

- build.cake
The `Nevermore.Extensions.DependencyInjection` project introduced in #118 is breaking the CI builds because the cake file expects the project to be packaged into a `nupkg`, but it's not being packaged. 
As a tactical fix to unblock the CI builds, this PR changes the `build.cake` file so that it no longer attempts to upload the `Nevermore.Extensions.DependencyInjection` nupkg file.
> Remove project from build.

- source/Nevermore/Advanced/ReadTransaction.cs
- source/Nevermore/RelationalStore.cs
In some conditions Nevermore isn't closing DB connections, which can lead to exhaustion of the connection pool. We've identified some places where connections aren't disposed. This PR fixes some of those places.
Build history: https://build.octopushq.com/buildConfiguration/OctopusDeploy_LIbraries_Nevermore?mode=builds#all-projects
The crux of this PR is this flow:
1. Calling code calls `BeginReadTransaction` or `BeginWriteTransaction`
2. A new `ReadTransaction` or `WriteTransaction` is created
3. The new transaction is added to the `RelationalTransactionRegistry` during the constructor
4. An exception is thrown during the call to `ReadTransaction.Open()` or `ReadTransaction.OpenAsync()`
Before this PR, the transaction would remain in the registry. After this PR, the transaction will be …
> Dispose of transactions when they fail to open.

- source/Nevermore.IntegrationTests/Model/MessageWithGuidId.cs
- source/Nevermore.IntegrationTests/Model/MessageWithGuidIdMap.cs
- source/Nevermore.IntegrationTests/Model/MessageWithIntId.cs
- source/Nevermore.IntegrationTests/Model/MessageWithIntIdMap.cs
- source/Nevermore.IntegrationTests/Model/MessageWithLongId.cs
- source/Nevermore.IntegrationTests/Model/MessageWithLongIdMap.cs
- source/Nevermore.IntegrationTests/Model/MessageWithStringId.cs
- source/Nevermore.IntegrationTests/Model/MessageWithStringIdMap.cs
- source/Nevermore.IntegrationTests/RelationalTransaction/DeleteFixture.cs
- source/Nevermore.IntegrationTests/RelationalTransaction/LoadFixture.cs
- source/Nevermore.IntegrationTests/SetUp/FixtureWithRelationalStore.cs
- source/Nevermore/Advanced/ReadTransaction.cs
- source/Nevermore/Advanced/WriteTransaction.cs
- source/Nevermore/CommandParameterValues.cs
- source/Nevermore/IWriteQueryExecutor.cs
- source/Nevermore/Util/DataModificationQueryBuilder.cs
Upgrade Nevermore version to the latest in `Octopus.Server`
[Octopus Server PR](https://github.com/OctopusDeploy/OctopusDeploy/pull/7965)
1. `LoadMany(IEnumerable<string> ids...)` failed when ids are of different lengths
**Solution:** Instead of using `SqlMetaData.InferFromValue`, we are using our own implementation to figure out the correct `SqlMetaData` to use
2. `Delete` and `DeleteAsync` support deletion by `object` id while we only support `string`, `int`, `long` and `Guid` types for ID column
**Solution:** Add the same overload methods for `Load` and `LoadAsync` to `Delete` and `DeleteAsync`, so we only support deletion by the supported ID types
Quality :heavy_check_mark:
Correctness ✔️ 
- For changes to the execution pipeline: …
> Add overloaded methods for Delete and DeleteAsync

- source/Nevermore.IntegrationTests/Advanced/StoreFixture.cs
- source/Nevermore/Transient/RetryManager.cs
This occurs when many connections are opened right after the store is created. The RetryManager will throw if one has already been set.
> Fixed a race condition setting the retry manager. 

- source/Nevermore.IntegrationTests/Advanced/RelationalTransactionRegistryFixture.cs
- source/Nevermore/RelationalStore.cs
Fixes https://github.com/OctopusDeploy/Nevermore/issues/130
This was fixed in 12.1 in #124 but not merged to `13.x`. I don't [like the change](https://github.com/OctopusDeploy/Nevermore/pull/124/files#diff-cb574f356346d8539d664d75fd6253faf8ab060fb248df62fd320b0f5842214fL51) to where the transaction is added to the registry so I intend to roll that back when I merge that branch.
> Correctly disposed transactions if there was an error opening them

- source/Nevermore.Extensions.DependencyInjection/Nevermore.Extensions.DependencyInjection.csproj
Nevermore CI builds were failing because we were trying to publish a `nupkg` that wasn't being generated. This PR adds some extra properties to the csproj file so that it will get packaged and published.
> Add nuget properties to csproj file.

- source/Nevermore.Benchmarks/Model/CustomerMap.cs
- source/Nevermore.IntegrationTests/Advanced/HooksFixture.cs
- source/Nevermore.IntegrationTests/Advanced/RowVersionFixture .cs
- source/Nevermore.IntegrationTests/Chaos/ChaosSqlCommand.cs
- source/Nevermore.IntegrationTests/Model/Customer.cs
- source/Nevermore.IntegrationTests/Model/CustomerMap.cs
- source/Nevermore.IntegrationTests/Model/DocumentWithRowVersion.cs
- source/Nevermore.IntegrationTests/Model/DocumentWithRowVersionMap.cs
- source/Nevermore.IntegrationTests/RelationalStoreFixture.cs
- source/Nevermore.IntegrationTests/SetUp/FixtureWithRelationalStore.cs
- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.InsertDocumentWithReadOnlyColumn.approved.txt
- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.InsertMultipleDocuments.approved.txt
- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.InsertSingleDocument.approved.txt
- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.InsertSingleDocumentWithDocumentIdAlreadySet.approved.txt
- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.InsertSingleDocumentWithTableNameAndHints.approved.txt
- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.InsertWithoutDefaultColumns.approved.txt
- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.Update.approved.txt
- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.UpdateWithHint.approved.txt
- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.UpdateWithRoWVersion.approved.txt
- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.cs
- source/Nevermore/Advanced/ReadTransaction.cs
- source/Nevermore/Advanced/WriteTransaction.cs
- source/Nevermore/CommandExecutor.cs
- source/Nevermore/IWriteQueryExecutor.cs
- source/Nevermore/Mapping/ColumnMapping.cs
- source/Nevermore/Mapping/DocumentMap.cs
- source/Nevermore/Mapping/IColumnMappingBuilder.cs
- source/Nevermore/StaleDataException.cs
- source/Nevermore/Util/DataModificationQueryBuilder.cs
It is possible for N > 1 independent operations to try to modify the same data at more or less the same time. 
This can lead to operations overriding each other data.
This PR adds support for [row versioning](https://docs.microsoft.com/en-us/sql/t-sql/data-types/rowversion-transact-sql?view=sql-server-ver15) which will ensure that the data in the database hasn't changed since it was retrieved and the update is safe to be applied.
Octopus Cloud is using background tasks to managed Cloud instances.  At the moment it is possible to for N > 1 tasks to modify the data of the same instance. To prevent this from happening we are adding 2 safety nets:
1. [Tasks will need to acquire a lock before they can modify a cloud instance](https://github.com/OctopusDeploy/Octofront/pull/2636)
2. Row …
> Added Row Versioning

- source/Nevermore/Advanced/WriteTransaction.cs
When we introduced async methods, we did not include the PopulateRelatedDocuments hook. This PR fills that gap so we can use async in our consumers.
> Calling the PopulateRelatedDocuments hook in our UpdateAsync method

- source/Nevermore.Analyzers/Nevermore.Analyzers.csproj
- source/Nevermore.Analyzers/NevermoreEmeddedSqlExpressionAnalyzer.cs
`netstandard2.1` analyzers don't work right in Visual Studio so we have to go backwards. Some incompatibilitly with ImmutableCollection.
> Downgraded to `netstandard2.0` so it works in Visual Studio

- source/Nevermore/Advanced/NevermoreDefaults.cs
- source/Nevermore/RelationalStoreConfiguration.cs
Update to the sql client - https://github.com/OctopusDeploy/Nevermore/commit/e50e1ae73af4a4c0dec93259812965071592abf2 
introduced a [breaking change](https://github.com/dotnet/SqlClient/blob/main/release-notes/2.0/2.0.0.md#breaking-changes-1), see - [SqlClient PR]( https://github.com/dotnet/SqlClient/pull/391)
We should now set a default for `TrustServerCertificate` to `true` to address this issue - [Internal Link](https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1621530394030900?thread_ts=1621530393.030800&cid=CNHBHV2BX)
> Add default for TrustServerCertificate

- source/Nevermore.Tests/RelationalStoreConfigurationFixture.cs
- source/Nevermore/Advanced/SqlConnectionStringHelpers.cs
- source/Nevermore/Nevermore.csproj
- source/Nevermore/RelationalStoreConfiguration.cs
`OverrideValueIfNotSet` doesn’t actually check the connection string to see if a value is set. Rather it compares a new builder's property values with that of the builder that we're wanting to override.
For example, if the connection string has boolean a property set explicitly, if the new builder has the same value set by default. `OverrideValueIfNotSet` compares properties and determines that both have the same default value and so it needs to override.
So if a consumer wants to explicitly set `Trust Server Certificate=False` in the string, OverrideValueIfNotSet treats that as being equal to the builder’s default and overrides it anyway with our override value, instead of ignoring it.
This fix updates how we validate and uses the builder's ShouldSerialize which checks if the value is in …
> Fix OverrideValueIfNotSet method and move to helpers

- source/Nevermore.Tests/QueryBuilderFixture/QueryBuilderFixture.ShouldGenerateDistinctForJoin.approved.txt
- source/Nevermore.Tests/QueryBuilderFixture/QueryBuilderFixture.cs
- source/Nevermore.Tests/QueryBuilderFixture/QueryBuilderStateFixture.cs
- source/Nevermore/Advanced/QueryBuilder.cs
- source/Nevermore/Advanced/SelectBuilder.cs
- source/Nevermore/Advanced/SourceQueryBuilder.cs
- source/Nevermore/ISelectBuilder.cs
- source/Nevermore/Querying/AST/IRowSelection.cs
- source/Nevermore/Querying/ICompleteQuery.cs
This change brings support to perform the `DISTINCT` sql operation to Nevermore. 
The approach here follows similar structure to the existing `TAKE` operation which has similar semantics albeit without the implicit ordering.
> Add support for `DISTINCT` select statement

- source/Nevermore.IntegrationTests/RelationalTransaction/LoadFixture.cs
- source/Nevermore/Advanced/ReadTransaction.cs
- source/Nevermore/Advanced/WriteTransaction.cs
- source/Nevermore/CommandExecutor.cs
- source/Nevermore/Transient/DbCommandExtensions.cs
- source/Nevermore/Transient/DbConnectionExtensions.cs
Found that there were a few async operations that did not use/accept a cancellation token:
- ExecuteNonQueryWithRetryAsync method in Nevermore.Transient.DbCommandExtensions - meaning it waited for timeout or completion
- OpenWithRetryAsync - meaning it would timeout rather than cancelled
- ReadResultsAsync - didn't accept a cancellation token, so you couldn't interrupt the reading of the resultset
Also found that on a case-sensitive DB server, the MinimumSubtotal parameter in the StoreAndLoadFromParameterizedRawSql test would fail (as Parameter turns it to lowercase).  The rest of the changes are resharper warnings.
> Extending cancellationToken's use in async calls

- source/Nevermore.Tests/QueryBuilderFixture/QueryBuilderFixture.cs
- source/Nevermore/Advanced/QueryBuilder.cs
- source/Nevermore/Advanced/SelectBuilder.cs
- source/Nevermore/Advanced/SourceQueryBuilder.cs
- source/Nevermore/IQueryBuilder.cs
- source/Nevermore/ISelectBuilder.cs
- source/Nevermore/Querying/AST/GroupBy.cs
- source/Nevermore/Querying/AST/Select.cs
Nevermore is based on a SQL database, but is missing some operations that can make queries simpler to write, and faster to run.
One missing feature is the GroupBy clause for obtaining aggregate information from the datastore.
While I was at it, I added a CountColumn helper method, which allows the (GroupBy) query to add a count column - mainly because the current Count() method expects that it finalises the query and is the only column returned (runs as scalar), whereas we want to include the count as one of the columns returned.
NOTE: Using GroupBy can easily result in queries that fall over, and at the moment there is no safeguard as to what columns are selected (eg, included in the group, or an aggregate), so be careful using it.
> Adding GroupBy Support 

- source/Nevermore.IntegrationTests/Advanced/HooksFixture.cs
- source/Nevermore.IntegrationTests/Advanced/NoJsonFixture.cs
- source/Nevermore.IntegrationTests/RelatedDocumentTableFixture.cs
- source/Nevermore.IntegrationTests/RelationalTransaction/DeleteFixture.cs
- source/Nevermore/Advanced/WriteTransaction.cs
- source/Nevermore/IWriteQueryExecutor.cs
This is reverting the signature change for requiring the key type on DELETE from https://github.com/OctopusDeploy/Nevermore/pull/149/files#diff-95a0a8cc5b6199fbc1e65c196e85c81d920a9d2a6112c86fc00a7598715f12cf
This makes it easier to call DELETE ([Slack conversation](https://octopusdeploy.slack.com/archives/C020HNMNT3L/p1626060225075400))
**Bumps major version**
`+semver:major`
> Don't require key type for DELETE if you already have the document (similar to UPDATE)

- source/Nevermore.IntegrationTests/Examples.cs
- source/Nevermore/Advanced/ReaderStrategies/Primitives/PrimitiveReaderStrategy.cs
This fixes a bug where `.Stream<CustomerId>` threw an exception about not being able to find a reader strategy.
This bug had surfaced in Octopus server, when doing a query along the lines of `.Stream<DeploymentId>("SELECT....")`
Apologies for the wall of whitespace changes that ended up in the files. The crux of the change is in `PrimitiveReaderStrategy`, and there is a new test to prove it now works, in `Examples.cs`
> Updated the primitive reader strategy so it will use custom TypeHandlers

- source/Nevermore.Analyzers.Tests/CodeCompiler.cs
- source/Nevermore.Analyzers.Tests/NevermoreSqlInjectionAnalyzerFixture.cs
- source/Nevermore.Analyzers/NevermoreSqlInjectionAnalyzer.cs
- source/Nevermore.Benchmarks/SetUp/IntegrationTestDatabase.cs
- source/Nevermore.IntegrationTests/SetUp/IntegrationTestDatabase.cs
This will ignore `nameof`, numbers and constants. They are very unlikely to represent SQLi vectors.
> Ignore certain types of interpolation for purposes of SQL injection

- source/Nevermore.IntegrationTests/Advanced/RowVersionFixture .cs
- source/Nevermore.IntegrationTests/Model/DocumentWithIdentityIdAndRowVersion.cs
- source/Nevermore.IntegrationTests/Model/IId.cs
- source/Nevermore/Advanced/WriteTransaction.cs
The error message produced in the case of a concurrency issue includes the name of the document type involved. This name is determined by using the generic type argument passed through to the `Update()` method. This type is not necessarily going to match the actual type of the document - it might be an interface implemented by the document, for example.
Take the document type name from the type stored on the mapping instead. This will be the actual type of the document.
```
Modification failed for 'IId`1' document with '1' Id because submitted data was out of date. Refresh the document and try again.
```
```
Modification failed for 'Channel' document with '1' Id because submitted data was out of date. Refresh the document and try again.
```
> Fix type name in concurrency error message

- source/Nevermore/Advanced/ReadTransaction.cs
Transaction name parameters are accepted by Nevermore but not propagated to SQL Server.
By the time an application becomes unresponsive it's very difficult to get a list of transactions from Nevermore, so we have to know to do it in advance.
With this change, we can just issue a `select * from sys.dm_tran_active_transactions` directly against SQL Server even if the application itself is unresponsive.
> Bug: pass transaction names through to SQL Server

- source/Nevermore/Advanced/WriteTransaction.cs
This PR fixes a bug with DeleteAsync. Currently DeleteAsync(document) was calling DeleteAsyncInternal which assumes an Id not the document itself.
> Fix DeleteAsync for documents

- source/Nevermore/RelationalStoreConfiguration.cs
currently our cache is per transaction (relates to #173). 
This change elevates the cache so that it is shared between all transactions created from the same config.
> Change TableColumnsCache scoping

- source/Nevermore.IntegrationTests/RelationalStoreFixture.cs
- source/Nevermore/Advanced/ReaderStrategies/Compilation/ExpressionHelper.cs
The Expression tree builder in the `ExpressionHelper` class has a built-in assumption that there is only one overload of the `Enum.Parse` method that is generic and accepts two arguments. This assumption has held for a long time. However, in .NET 6.0 a new overload has been added to the `Enum` class that matches these conditions, and the builder breaks.
This change makes the selection of the `Enum.Parse` overload more specific by also constraining the argument types expected. There's also a bit of a refactor of the `ExpressionHelper` class thrown in for good measure.
Fixes #170
> ExpressionHelper fails on .NET 6.0

- source/Nevermore.Tests/QueryBuilderFixture/QueryBuilderFixture.cs
- source/Nevermore/Advanced/QueryBuilder.cs
- source/Nevermore/Advanced/QueryBuilders/SourceQueryBuilder.cs
- source/Nevermore/Advanced/SelectBuilders/JoinSelectBuilder.cs
- source/Nevermore/Advanced/SelectBuilders/SelectBuilderBase.cs
- source/Nevermore/Advanced/SelectBuilders/SubquerySelectBuilder.cs
- source/Nevermore/Advanced/SelectBuilders/TableSelectBuilder.cs
- source/Nevermore/Advanced/SelectBuilders/UnionSelectBuilder.cs
- source/Nevermore/IQueryBuilder.cs
- source/Nevermore/ISelectBuilder.cs
- source/Nevermore/Querying/AST/Option.cs
- source/Nevermore/Querying/AST/Select.cs
This change adds support for Option query hints as shown below.
The Option clause has support for multiple query hints so I did the same here.
This would allow us to use `OPTIMIZE FOR UNKNOWN` to avoid parameter sniffing issues as described [here](https://techcommunity.microsoft.com/t5/sql-server-blog/optimize-for-unknown-8211-a-little-known-sql-server-2008-feature/ba-p/383498) and [here](https://blog.sqlauthority.com/2019/12/21/sql-server-parameter-sniffing-and-optimize-for-unknown/).
`OPTIMIZE FOR UNKNOWN` can be useful to solve this problem:
"An application that I work with presented me with an interesting dilemma; It wanted to utilize the benefits of plan reuse but the parameter values that the application initially sends to SQL Server are not representative of the values passed in …
> Add query hint support

- source/Nevermore.IntegrationTests/QueryableIntegrationFixture.cs
- source/Nevermore/Advanced/Queryable/NevermoreQueryableExtensions.cs
- source/Nevermore/Advanced/Queryable/QueryProvider.cs
- source/Nevermore/Advanced/Queryable/QueryTranslator.cs
- source/Nevermore/Advanced/Queryable/QueryType.cs
- source/Nevermore/Advanced/Queryable/SqlExpressionBuilder.cs
Adds `Hint` extension to `IQueryable` to be able to specify table hints in the query.
Adds `RawDebugQuery` extension to `IQueryable` to be able to see debug view the query like possible with using `Query`.
> Add Hint and RawDebugView to Queryable

- source/Nevermore.IntegrationTests/QueryableIntegrationFixture.cs
- source/Nevermore/Advanced/Queryable/QueryTranslator.cs
Fixes an issue where properties wouldn't map to columns for querying when the queried document type did not exactly match the type defined in the document map. This is a legitimate case for polymorphic document types.
> IQueryable - Handle polymorphic documents

- source/Nevermore.Analyzers.Tests/NevermoreEmbeddedSqlExpressionAnalyzerFixture.cs
- source/Nevermore.Analyzers/NevermoreEmeddedSqlExpressionAnalyzer.cs
Fix analyzer crash when CommandType is set on CommandParameterValues, as part of an object initializer.
Analyzer was crashing with:
```
Analyzer 'Nevermore.Analyzers.NevermoreEmbeddedSqlExpressionAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
```
Full stack trace from diagnostic build log was:
```
CSC : warning AD0001: Analyzer 'Nevermore.Analyzers.NevermoreEmbeddedSqlExpressionAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
Exception occurred with following context: (TaskId:134)
Compilation: Octofront.Core (TaskId:134)
SyntaxTree: /Users/anon/myproject/Persistence/TransactionExtensions.cs (TaskId:134) …
```
> Fix analyzer crash when CommandType is set on CommandParameterValues

- source/Nevermore.IntegrationTests/QueryableIntegrationFixture.cs
- source/Nevermore/Advanced/Queryable/QueryProvider.cs
- source/Nevermore/CommandExecutor.cs
When doing the following query:
`tx.Query<DodgyProduct>().Where(x => x.Name == "iphane").FirstOrDefaultAsync()`
We'd get an exception: `System.InvalidCastException: Object must implement IConvertable`. This was bubbling up from `(TResult)Convert.ChangeType(await FirstOrDefaultAsync(asyncStream, cancellationToken), typeof(TResult))` in the `QueryProvider.ExecuteAsync` which is only excercised through `IQueryable.GetFirstOrDefaultAsync` which we didn't have a test that hit. 
When it tries to convert from `DodgyProduct` to `Product`, it does a type comparison and `typeof(DodgyProduct) != typeof(Product)` so it was failing the convert type. The solution here is to not use ConvertType (which we believe was chosen as IAsyncEnumerable doesn't have a `.Cast` method like IEnumerable does, which is …
> Fixing issue with casting for types that inherit from base type with FirstOrDefaultAsync

- source/Nevermore.IntegrationTests/Advanced/ViewMappingFixture.cs
- source/Nevermore/TableColumnNameResolvers/JsonLastTableColumnNameResolver.cs
In Nevermore 15.0.1 (Jul 2021) and earlier it was possible to map and query a view. However with the change where it looks at the schema for what columns exist, it fails to add columns to the query (despite them being included in the mapping).
This re-enabled this functionality and allows for querying of views.
Let me know if there is a different preferred way to query views.
> Re-enable the querying of views

- source/Nevermore.IntegrationTests/Advanced/MissingTableFixture.cs
- source/Nevermore/TableColumnNameResolvers/JsonLastTableColumnNameResolver.cs
Previously it would run the query with no column specification, resulting in the following error:
```
No columns found for table or view 'TestSchema.Missing'. The table or view likely does not exist in that schema.", but "Error while executing SQL command in transaction 'NonParallelWorker': Incorrect syntax near the keyword 'FROM'.
The command being executed was:
SELECT 
FROM [TestSchema].[Missing]
ORDER BY [Id]
```
> Throw an exception when the table/view doesn't exist

- source/Nevermore.Benchmarks/SetUp/IntegrationTestDatabase.cs
- source/Nevermore.IntegrationTests/SetUp/IntegrationTestDatabase.cs
- source/Nevermore/Advanced/ReadTransaction.cs
- source/Nevermore/Nevermore.csproj
- source/Nevermore/Transient/RetryManagerSqlExtensions.cs
- source/Nevermore/Transient/TransactionExtensions.cs
- source/Nevermore/TransientFaultHandling.cs
Octopus Deploy dev teams have noticed transient connectivity issues when calling `BeginTransaction` in `ReacTransaction.cs`. 
We are also behind 2 versions of SqlClient that may have beneficial bug fixes or performance improvements..
The objective of this PR is to:
- Bump the version of SqlClient
- Wrap these calls with retry logic provided by the RetryManager
[Slack Thread](https://octopusdeploy.slack.com/archives/C02SY496BAM/p1644994741806619)
TODO: get these running (currently hitting errors)
TODO: Same
> Add retry for BeginTransaction

- source/Nevermore.IntegrationTests/Advanced/JsonLastTableColumnResolverFixture.cs
- source/Nevermore.IntegrationTests/Advanced/MissingTableFixture.cs
- source/Nevermore.IntegrationTests/SetUp/SchemaGenerator.cs
- source/Nevermore.Tests/CachingTableColumnNamesFixture.cs
- source/Nevermore/RelationalStore.cs
- source/Nevermore/RelationalStoreConfiguration.cs
- source/Nevermore/TableColumnNameResolvers/CachingTableColumnNameResolver.cs
- source/Nevermore/TableColumnNameResolvers/JsonLastTableColumnNameResolver.cs
Previously in https://github.com/OctopusDeploy/Nevermore/pull/169 we changed the default behaviour of Nevermore to use a JSON last column table name resolver, which means queries would look like:
`SELECT Name,Age,Type,JSON FROM Person` instead of `SELECT * FROM Person` to avoid the issue of having to have the JSON column last when using the Type column in a polymorphic document structure.
After some discussion https://octopusdeploy.slack.com/archives/C020HNMNT3L/p1643763058763589 (internal link), I proposed that having this as the default behaviour probably isn't correct https://octopusdeploy.slack.com/archives/C02KHED7RRU/p1643837352093699 (internal link), and we're going back to the previous behaviour, with us overriding that in Octopus Server where we needed this change. 
Since we no …
> Change default TableColumnNameResolver back to Select All

- source/Nevermore/TableColumnsCache.cs
Change `TableColumnsCache` from internal to public, as it can be used with our public contract `CachingTableColumnNameResolver`.
> Make TableColumnsCache public

- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.InsertWithBaseColumns.approved.txt
- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.UpdateWithBaseColumns.approved.txt
- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.cs
- source/Nevermore/RelationalJsonContractResolver.cs
The `RelationalJsonContractResolver` is responsible for determining which properties should be serialized in the JSON blob. It does this by using the declaring type of the property to fetch the document map and see whether it's mapped to a column, in which case it should be excluded.
This doesn't work if the property is declared by a base type that doesn't have a document map. In this case, if the derived type maps the property to a column, the property will be written to the JSON blob and the column.
Fix the resolver to always use the type for the contract being built to find the document map.
> Fix JSON Contract Resolver to support columns from base types

- source/Nevermore.IntegrationTests/Advanced/ConcurrentAccessFixture.cs
- source/Nevermore.IntegrationTests/Advanced/JsonLastTableColumnResolverFixture.cs
- source/Nevermore.Tests/DeadlockAwareLockFixture.cs
- source/Nevermore/Advanced/DeadlockAwareLock.cs
- source/Nevermore/Advanced/DeadlockException.cs
- source/Nevermore/Advanced/ReadTransaction.cs
- source/Nevermore/Advanced/ThreadSafeAsyncEnumerable.cs
- source/Nevermore/Advanced/ThreadSafeEnumerable.cs
- source/Nevermore/Advanced/WriteTransaction.cs
- source/Nevermore/IRelationalStoreConfiguration.cs
- source/Nevermore/Nevermore.csproj
- source/Nevermore/RelationalStore.cs
- source/Nevermore/RelationalStoreConfiguration.cs
- source/Nevermore/TableColumnNameResolvers/JsonLastTableColumnNameResolver.cs
- source/Nevermore/UniqueParameterNameGenerator.cs
Applications consuming Nevermore transactions have previously not been able to perform concurrent operations on a single Nevermore transaction (unless, in some cases, MARS was emabled). This has led to operations which _should_ have been transactional being split into multiple transactions for mostly performance reasons, at the cost of atomicity.
E.g.
```
machines
.Do(m => healthCheckService.CheckHealthFor(m))
.Done()
// No worries, but also slow.
```
but simply adding `.AsParallel()` or a `Task.WhenAll(...)` equivalent for performance improvement is not feasible.
```
machines
.AsParallel()  // Not going to end well.
.Do(m => healthCheckService.CheckHealthFor(m))
.Done()
```
This leads to constructs like this:
```
machines
.AsParallel()
.Do(m => {
using var transaction = …
```
> Thread-safe access to Nevermore transaction objects.

- source/Nevermore.IntegrationTests/Advanced/ConcurrentAccessFixture.cs
- source/Nevermore.Tests/DeadlockAwareLockFixture.cs
- source/Nevermore/Advanced/ReadTransaction.cs
- source/Nevermore/Advanced/ThreadSafeAsyncEnumerable.cs
This bug was noticed by @pawelpabich [here](https://github.com/OctopusDeploy/Nevermore/pull/192#pullrequestreview-957294089).
It's currently a non-functional bug as it _just so happens_ that the type we're passing in is actually a `DeadlockAwareLock` but things will go sneakily bad if we pass in a bare `SemaphoreSlim` at any later date.
We'd initially intended to remove the inheritance of `SemaphoreSlim` from `DeadlockAwareLock` but we get too many nice extensions on `SemaphoreSlim` from `Nito.AsyncEx` which we'd have to reimplement so it actually looks safer to keep the inheritance but have the compiler make it impossible to pass an incorrect type around.
> Fix bug where we accept any SemaphoreSlim instead of a DeadlockAwareLock

- source/Nevermore.Tests/QueryBuilderFixture/QueryBuilderFixture.ShouldGeneratePaginateWithMultipleSpecifiedColumns.approved.txt
- source/Nevermore.Tests/QueryBuilderFixture/QueryBuilderFixture.ShouldGeneratePaginateWithSpecifiedColumn.approved.txt
- source/Nevermore.Tests/QueryBuilderFixture/QueryBuilderFixture.ShouldGeneratePaginateWithSpecifiedColumnAndNoSort.approved.txt
- source/Nevermore.Tests/QueryBuilderFixture/QueryBuilderFixture.cs
- source/Nevermore/Advanced/QueryBuilder.cs
- source/Nevermore/Advanced/SelectBuilders/SelectBuilderBase.cs
- source/Nevermore/ISelectBuilder.cs
Fixes a bug with SQL generation when using specified columns.
For instance
```              
var ids = await read.Query<Table>()
.Column(t => t.Id)
.AsType<string>()
.ToListAsync(skip, batchSize);
```
resulted in a SQL of 
```
SELECT *
FROM (
SELECT [Id],
*,
ROW_NUMBER() OVER (ORDER BY [Id]) AS RowNum
FROM [dbo].[Table]
) ALIAS_GENERATED_1
WHERE ([RowNum] >= @_minrow)
AND ([RowNum] <= @_maxrow)
ORDER BY [RowNum]
```
which would throw an error of
> The column 'Id' was specified multiple times for 'ALIAS_GENERATED_1'.
because we were including `*` in the subquery.
The fix is to only add the default columns if there is not already specified columns.
> Fix SQL generation when paging with specified columns

- source/Nevermore/Advanced/WriteTransaction.cs
- source/Nevermore/RelatedDocuments/EmptyRelatedDocumentStore.cs
- source/Nevermore/RelatedDocuments/IRelatedDocumentStore.cs
Currently the `IRelatedDocumentStore` only has synchronous methods. These methods are called from the async methods on `IWriteQueryExecutor`, meaning they're likely to block threads.
This PR introduces async versions of these methods to avoid the blocking.
It also corrects an ambiguity problem in the `IRelatedDocumentStore` interface.
This is a breaking change to the interface, so will require a major bump.
> Async Support on IRelatedDocumentStore

- source/Nevermore.Tests/QueryBuilderFixture/QueryBuilderFixture.cs
- source/Nevermore/Advanced/QueryBuilder.cs
The `DistinctAsync()` method of the query builder does not exclude the default ORDER BY clause, like its synchronous counterpart.
Fixes https://github.com/OctopusDeploy/Nevermore/issues/201
> Fix SQL generation bug when using DistinctAsync

- global.json
Also turn off building with a pre-release .NET version if one ever showed up
> Update global.json to explicitly use .NET 6

- source/Nevermore/CommandExecutor.cs
The `WrapException` method rethrows an `Exception` when a `SqlException` is encountered. However, for certain types of `SqlExceptions`, it doesn't include the original `SqlException` as part of the rethrown `Exception`.
There are instances of consuming code that depends on the presence of this `SqlException` as an inner exception that break when more `Number`s are captured by this condition
```
if (ex is SqlException {Number: 1205 or 1222 or -2})
```
as it causes the raised `Exception` to exclude wrapping any inner exception.
No inner exception when deadlocks, timeouts and row lock timeouts are encountered. If other types of `SqlException`s are added in the same fashion, when those exceptions are raised, they will also stop containing inner exceptions.
`SqlException` as an inner exception …
> Ensured rethrown SqlExceptions are being wrapped to preserve consumer exception handling assumptions

- source/Nevermore.Tests/Queryable/QueryableExtensionsFixture.cs
- source/Nevermore/Advanced/Queryable/NevermoreQueryableExtensions.cs
When using the `Enumerable.AsQueryable` extension method, the returned `IQueryable` will be backed by an [`EnumerableQuery`](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Linq.Queryable/src/System/Linq/EnumerableQuery.cs) provider. This class executes queries by walking the expression tree looking for `IQueryable` extension method calls (`Where()`, `Select()`, etc.), and translates them to their `IEnumerable` counterparts. It then compiles the expression and executes it directly.
The `Hint()` extension method that Nevermore provides doesn't have an `IEnumerable` counterpart, so when it's encountered the translation fails with the following exception:
```
System.InvalidOperationException: There is no method 'Hint' on type …
```
> Allow translation of Hint extension by EnumerableQuery

- source/Nevermore.Analyzers.Tests/Nevermore.Analyzers.Tests.csproj
- source/Nevermore.Benchmarks/Nevermore.Benchmarks.csproj
- source/Nevermore.IntegrationTests/Advanced/InstanceTypesFixture.cs
- source/Nevermore.IntegrationTests/Nevermore.IntegrationTests.csproj
- source/Nevermore.Tests/Nevermore.Tests.csproj
This PR updates the test projects to target `net6.0`, as `netcoreapp3.1` is EOL in December.
As part of the update, test NuGet packages were also bumped to the latest versions, and unused packages were removed.
> Update tests to target net6.0

- .github/CODEOWNERS
- CONTRIBUTING.md
- README.md
Nevermore doesn't have a contributing guide and also it wasn't clear what role Paul plays in the future of Nevermore. 
This PR tries to fill both gaps. I assumed that we do want external contributions.
Details: https://octopusdeploy.slack.com/archives/C01MSG3LZ5M/p1619682265043100
This PR is my understanding of ^ conversation. Happy to change things if I got anything wrong.
> Contributing guide

- source/Nevermore/Advanced/WriteTransaction.cs
- source/Nevermore/Util/DataModificationQueryBuilder.cs
- source/Nevermore/Util/EnumerableExtensions.cs
It was identified that for `insert many` transaction, there is a good possibility on exceeding 2100 SQL parameters limit, which caused `SQL Exception`.
This update is to process transaction in batches to avoid this issue
> Add batch processing for insert many transaction 

- source/Nevermore.Analyzers/Nevermore.Analyzers.csproj
- source/Nevermore.Benchmarks/Nevermore.Benchmarks.csproj
- source/Nevermore.Contracts/Nevermore.Contracts.csproj
- source/Nevermore.Extensions.DependencyInjection/Nevermore.Extensions.DependencyInjection.csproj
- source/Nevermore/Nevermore.csproj
This work is to address [issue 216](https://github.com/OctopusDeploy/Nevermore/issues/216).
Updating packages to prepend `Octopus`, a reserved prefix on nuget.org
> Adding Octopus prefix to avoid references dependency confusion

- source/Nevermore/Advanced/ReaderStrategies/Documents/DocumentReaderStrategy.cs
When two types that look the same, with the same name but belonging to two different namespaces try to access the same data, things go 💥 and the first type wins, second type says it can't see anything.
> Use full name for types in the cache key

- source/Nevermore/Transient/SqlDatabaseTransientErrorDetectionStrategy.cs
This is an alternative PR to #217.
We (Cloud Platform) are frequently hitting the following error/exception when executing our E2E tests which utilise a SQL Azure Elastic Pool.
`SQL Error 10936 - Resource ID : %d. The request limit for the elastic pool is %d and has been reached.`
While adding this error code to the list of transient codes in Nevermore, I noticed that the list is considerably different/outdated(?) when compared to that of EF Core - where this list was originally sourced.
This PR updates the list of transient error codes to match those [now defined in EF Core](https://github.com/dotnet/efcore/blob/3a428827470ed6806739715b7607b8e7752084d8/src/EFCore.SqlServer/Storage/Internal/SqlServerTransientExceptionDetector.cs)
> Updates list of SQL Server transient error codes to match those defined in EF Core

- source/Nevermore/Advanced/Serialization/NewtonsoftDocumentSerializer.cs
The `NewtonsoftDocumentSerializer` makes use of a [`RecycableMemoryStreamManager`](https://github.com/microsoft/Microsoft.IO.RecyclableMemoryStream) to efficiently use and re-use memory streams. However, the manager is configured in such a way as to be quite inefficient with memory.
On construction, the `RecyclableMemoryStreamManager` takes three arguments:
- Block Size
- Large Buffer Multiple
- Maximum Large Buffer Size
The last two are of interest. For pooling large buffers of memory, a series of pools is created with varying sizes. These sizes are (1 * Large Buffer Multiple), (2 * Large Buffer Multiple), etc. up to the Maximum Large Buffer Size. The idea being to have a fairly small variety of sizes to choose from, with the smaller pools being more densely populated than the larger …
> Fix incorrectly configured recyclable memory stream pool sizes

- source/Nevermore.IntegrationTests/Advanced/InstanceTypesFixture.cs
- source/Nevermore.IntegrationTests/Model/BrandTypeResolver.cs
- source/Nevermore.IntegrationTests/Model/ProductConverter.cs
- source/Nevermore.IntegrationTests/QueryBuilderIntegrationFixture.cs
- source/Nevermore.IntegrationTests/QueryableIntegrationFixture.cs
- source/Nevermore.IntegrationTests/RelationalStoreFixture.cs
- source/Nevermore.Tests/Column/ColumnExpressionTests.cs
- source/Nevermore.Tests/QueryBuilderFixture/QueryBuilderFixture.cs
- source/Nevermore.Tests/QueryBuilderFixture/QueryBuilderStateFixture.cs
- source/Nevermore.Tests/QueryBuilderFixture/VariableCasingFixture.cs
- source/Nevermore/Advanced/InstanceTypeResolvers/IInstanceTypeRegistry.cs
- source/Nevermore/Advanced/InstanceTypeResolvers/IInstanceTypeResolver.cs
- source/Nevermore/Advanced/InstanceTypeResolvers/InstanceTypeRegistry.cs
- source/Nevermore/Advanced/QueryBuilders/TableSourceQueryBuilder.cs
- source/Nevermore/Advanced/Queryable/SqlExpressionBuilder.cs
- source/Nevermore/Advanced/ReadTransaction.cs
- source/Nevermore/Advanced/ReaderStrategies/Documents/DocumentReaderContext.cs
Nevermore is able to store multiple document types in a single table. However, when building queries it is unable to differentiate between the types. This results in the wrong result being generated in certain cases, such as counting documents of a certain type.
For example, a base type `Product` has two derived types, `ProductA` and `ProductB`. These are stored in the `[dbo].[Product]` table, with a `[Type]` column with either the value "ProductA" or "ProductB". When trying to count the number of `ProductB` documents like:
``` CSharp
transaction.Query<ProductB>().Count()
```
will generate the following SQL
``` SQL
SELECT COUNT(*) FROM [dbo].[Product]
```
This will count instances of both `ProductA` and `ProductB`.
Currently the filter must be added manually because type resolvers don't …
> Allow query generator to discriminate by type

- source/Nevermore.IntegrationTests/QueryableIntegrationFixture.cs
- source/Nevermore/Advanced/Queryable/SqlExpressionBuilder.cs
Fixes #238 
The generated `WHERE` clause for an empty collection needed to change when using the `NOT IN` operator.
In that case, we want to include _all_ results, so a custom where of `1 = 1` is the way to go. When it's an `IN` operator, we do `1 = 0` as we shouldn't include _any_ results in that case
> Fixed NOT IN not working with empty collection

- source/Nevermore/Advanced/DeadlockAwareLock.cs
- source/Nevermore/Advanced/Hooks/HookRegistry.cs
- source/Nevermore/Advanced/QueryBuilder.cs
- source/Nevermore/Advanced/Queryable/NevermoreQueryableExtensions.cs
- source/Nevermore/Advanced/Queryable/QueryProvider.cs
- source/Nevermore/Advanced/ReadTransaction.cs
- source/Nevermore/Advanced/ThreadSafeAsyncEnumerable.cs
- source/Nevermore/Advanced/WriteTransaction.cs
- source/Nevermore/CommandExecutor.cs
- source/Nevermore/Nevermore.csproj
- source/Nevermore/RelationalStore.cs
- source/Nevermore/Transient/DbCommandExtensions.cs
- source/Nevermore/Transient/RetryPolicy.cs
The boolean passed to `ConfigureAwait` allows you to specify whether or not the callback after the `await` is forced to be invoked on the original `SynchronizationContext`. If unspecified, the default value is `true`. Under most circumstances this is not an issue, but for library code it's a good idea to specify `false` so the caller can decide.
This PR enables the [CA2007](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2007) warning as an error to help guide us toward using `ConfigureAwait(false)`, and fixes all violations.
> ConfigureAwait(false) wherever we await a task

- source/Nevermore/Transient/SqlDatabaseTransientErrorDetectionStrategy.cs
If acquiring a SQL connection from the connection pool times out due to no connections being available, the operation will fail with an error. This class of error is currently not identified as a transient error, though other timeout errors are. This means that encountering this error would fail the operation immediately without retrying.
Add the exception raised by SqlClient when a pooled connect timeout occurs to the list of transient errors that could be retried. It is no different from other types of timeout errors, except that it is raised as an `InvalidOperationException` instead of a `SqlException`.
> Retry pooled connection timeout

- .nuke/parameters.json
- build/Build.cs
I could not get Nuke to build on my machine without this change.
`SourceDirectory` uses the full path and fixes the problem.
This is the command that was not working: `build.cmd --Target Restore`
> Fix the project file reference on Nuke

- source/Nevermore.Analyzers.Tests/Nevermore.Analyzers.Tests.csproj
- source/Nevermore.Analyzers/Nevermore.Analyzers.csproj
- source/Nevermore.IntegrationTests/Nevermore.IntegrationTests.csproj
`Nevermore.Analyzers` references older versions of `Microsoft.CodeAnalysis` libraries. The different base analyser versions can cause issues in other projects.
For example, below is a typical warning message from a referencing project. The `3.0.0-beta2.20059.3` version is implicitly included in the older `Microsoft.CodeAnalysis` `v3.5.0` libraries.
```
Warning	CS8032	An instance of analyzer 
Microsoft.CodeAnalysis.CSharp.Analyzers.MetaAnalyzers.CSharpDiagnosticAnalyzerFieldsAnalyzer
cannot be created from ...\microsoft.codeanalysis.analyzers\3.0.0-beta2.20059.3\analyzers\dotnet\cs\Microsoft.CodeAnalysis.CSharp.Analyzers.dll
```
This PR:
* Removes redundant `Microsoft.CodeAnalysis` packages
* Updates remaining analyzer packages to their latest versions
* Removes a no-longer-support …
> Update CSharp analyzer base packages and remove legacy compat package

- source/Nevermore.Analyzers.Tests/Nevermore.Analyzers.Tests.csproj
- source/Nevermore.Analyzers/Nevermore.Analyzers.csproj
This PR downgrades `Microsoft.CodeAnalysis.*` pacakges to `4.3.1` to properly support the .NET 6 compiler.
As part of the `Microsoft.CodeAnalysis.*` cleanup in #249, the packages were updated to `4.5.0`. While this version works with a .NET 7 compiler (regardless of the project's target .NET version), it will not work with pinned .NET 6 compiler (e.g. via `global.json`).
`Microsoft.CodeAnalysis.*` vesion numbers track Roslyn version numbers. .NET 6 includes Rolsyn `4.3.x` only. C# analyzers (such as `Microsoft.CodeAnalysis.*`) are built to require specific compiler features, based on their versions.
> Downgrade Microsoft.CodeAnalysis.* packages to 4.3 for .NET 6 compiler support

- source/Nevermore.IntegrationTests/QueryableIntegrationFixture.cs
- source/Nevermore/Advanced/Queryable/IAsyncQueryProvider.cs
- source/Nevermore/Advanced/Queryable/INevermoreQueryable.cs
- source/Nevermore/Advanced/Queryable/Query.cs
- source/Nevermore/Advanced/Queryable/QueryProvider.cs
This PR adds the minimum requirements to properly support async enumeration over the results of a query via Nevermore's `IQueryable` implementation. It's backed by `StreamAsync` which already existed and works well, so not much had to be done.
It's possible to go further with this and add an `IAsyncEnumerable` layer on top which can provide `async foreach` support and nicer cancellation token ergonomics among other things, but that's left up to consumers.
To confirm this works as intended (minimising the amount of information kept in memory while iterating) I ran the following code locally and used the debugger to verify the number of `Customer` instances on the heap did not grow.
```csharp
[Test]
public async Task TestingMemoryUsage()
{
using var t = Store.BeginTransaction();
foreach …
```
> Add async enumeration support to INevermoreQueryable

- source/Nevermore.IntegrationTests/RelationalTransaction/TransactionTimerFixture.cs
- source/Nevermore/Advanced/ReadTransaction.cs
- source/Nevermore/Diagnostics/DefaultTransactionLogger.cs
- source/Nevermore/Diagnostics/ITransactionLogger.cs
- source/Nevermore/IRelationalStoreConfiguration.cs
- source/Nevermore/RelationalStoreConfiguration.cs
Log how long each transaction was open for. This follows the same pattern for logging the query duration. The server can then hook into the `ITransactionLogger` to provide telemetry data.
1 of 2 PRs for [sc-47869]. The server PR to be merged after this is https://github.com/OctopusDeploy/OctopusDeploy/pull/17998.
> Log transaction duration

- source/Nevermore/Advanced/Queryable/QueryTranslator.cs
- source/Nevermore/Advanced/ReadTransaction.cs
When reading documents where the JSON is large, 4MB takes about 22 seconds. The time increases quickly from there to hours for 40MB.
It does seem that lots of node CPU is used as well.
This is due to https://github.com/dotnet/SqlClient/issues/593#issuecomment-642831448.
See OctopusDeploy/Issues#8076
[sc-48263]
When translating a Linq expression to a `PreparedCommand`, the resulting command will now have the `SequentialAccess` and `SingleResult` behaviour flags enabled.
This is also consistent with other usages of the `PreparedCommand` constructor, as well as [Microsoft's own advice for streaming large BLOBs](https://learn.microsoft.com/en-us/dotnet/framework/data/adonet/sqlclient-streaming-support).
While I'm in the area, I figured I'd add the `SingleRow` flag to some `ExecuteScalar` …
> Enable `SequentialAccess` for queries translated by the `QueryTranslator`

- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.DeleteByIdWithInheritedTypedKey.approved.txt
- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.DeleteByIdWithTypedKey.approved.txt
- source/Nevermore.Tests/Util/DataModificationQueryBuilderFixture.cs
- source/Nevermore/Util/DataModificationQueryBuilder.cs
Relaxes the type check in `PrepareDelete` and `GetDocumentParameters` to allow inherited types of the DocumentMap id column key type.
The key type check on the [`PrepareLoad` in `ReadTransaction`](https://github.com/OctopusDeploy/Nevermore/blob/b22d050365396e975c45f024dbb28de18bbb95b9/source/Nevermore/Advanced/ReadTransaction.cs#L676-L677) allows for inherited types to be passed in because we check that the mapping id column type matches `TKey` rather than the specific runtime type.
In [`PrepareDelete` in `DataModificationQueryBuilder`](https://github.com/OctopusDeploy/Nevermore/blob/master/source/Nevermore/Util/DataModificationQueryBuilder.cs#L127-L129) called by `WriteTransaction`, we do an exact comparison against the runtime type of the identifier. If it is not an exact type match, …
> Allow inherited types in type check in DataModificationQueryBuilder

- source/Nevermore.Analyzers.Tests/NevermoreFixture.cs
- source/Nevermore.Analyzers.Tests/NevermoreQueryableAnalyzerFixture.cs
- source/Nevermore.Analyzers/Descriptors.cs
- source/Nevermore.Analyzers/Issue.cs
- source/Nevermore.Analyzers/NevermoreQueryableAnalyzer.cs
- source/Nevermore.Analyzers/NevermoreQueryableVisitor.cs
- source/Nevermore.Analyzers/NevermoreWhereExpressionVisitor.cs
Adds a Roslyn Analyzer that raises compiler errors when an unsupported `IQueryable` method is invoked. This analyzer only targets calls to Nevermore types, i.e: `IReadQueryExecutor.Queryable<T>().Single()` and doesn't affect other calls to `IQueryable`, i.e: `myList.AsQueryable().Single()`.
Also makes the visitors public so that they can be accessed in Octopus Server and re-purposed.
[sc-53501]
> Add a Roslyn Analyzer for unsupported IQueryable methods

- source/Nevermore.Analyzers.Tests/NevermoreQueryableAnalyzerFixture.cs
- source/Nevermore.Analyzers/NevermoreQueryableAnalyzer.cs
Updates the `IQueryable` analyser to ignore non `IQueryable` methods, e.g: `.ToList()`.
> Ignore non-IQueryable methods

- source/Nevermore.IntegrationTests/QueryableIntegrationFixture.cs
- source/Nevermore/Advanced/Queryable/QueryTranslator.cs
- source/Nevermore/LikeComparisonExtensions.cs
- source/Nevermore/QueryBuilderWhereExtensions.cs
When querying a value with `.Contains`, the resulting SQL is a `WHERE foo LIKE %{value}%` clause. When `value` contains special characters (`[` or `%`) the results can be unpredictable.
> Escape `LIKE` comparison so that `[` and `%` can be used in queries

- source/Nevermore.IntegrationTests/Model/Machine.cs
- source/Nevermore.IntegrationTests/QueryableIntegrationFixture.cs
- source/Nevermore/Advanced/Queryable/PropertyInfoExtensions.cs
When performing a `.Where` query against a property of type `DateTimeOffset`, it was incorrectly being identified as a non-scalar type, meaning nevermore tried to use `JSON_QUERY`, as opposed to `JSON_VALUE`.
This is because the TypeCode returned is `Object`.
This PR just updates the `IsScalar` to check certain predefined scalar types before falling back on the `GetTypeCode` check
> Correctly identify DateTimeOffset JSON properties as scalar

- source/Nevermore/Advanced/ReadTransaction.cs
- source/Nevermore/IRelationalStore.cs
- source/Nevermore/RelationalStore.cs
- source/Nevermore/Transient/DbCommandExtensions.cs
- source/Nevermore/Transient/DbConnectionExtensions.cs
- source/Nevermore/Transient/RetryPolicy.cs
Cancellation tokens weren't being passed to `OpenAsync`. This means that failure to acquire a connection (e.g. timing out trying to obtain a connection from the SQL connection pool) cannot be cancelled. This PR resolves that.
> Async and cancellation improvements

- source/Nevermore.IntegrationTests/Advanced/CustomKeyAllocatorFixture.cs
- source/Nevermore/IRelationalStoreConfiguration.cs
- source/Nevermore/RelationalStore.cs
- source/Nevermore/RelationalStoreConfiguration.cs
This allows the configuration of a custom `IKeyAllocator` implementation which will be used to provide the numerical suffix when generating Ids. We intend to use this to synchronise key allocation with documents that are outside of the control of Nevermore.
> Allow using a custom key allocator by setting the `KeyAllocatorFactory` configuration

- source/Nevermore/Advanced/ReadTransaction.cs
- source/Nevermore/CommandParameterValues.cs
There are two ways to assign primary key handlers to documents. One is to register the handler with the `PrimaryKeyHandlers` collection in the configuration, the other is to assign a `PrimaryKeyHandler` to the `IdColumn` in the document map. The end result of both is the same, because when the document map is built, if there is no deliberately assigned `PrimaryKeyHandler`, then it will set the appropriate value from the `PrimaryKeyHandlers` in the configuration.
As a result, the correct way to access the `PrimaryKeyHandler` when you need it for a document type is _always_ to look it up via the document map. If you look it up via the configuration, you will end up using the wrong primary key handler (or failing to find one altogether) if the consumer has assigned a custom …
> Fix AddTable using the wrong source for the PrimaryKeyHandler

- source/Nevermore/RelationalStoreConfiguration.cs
Previously the only way to use a custom primary key handler registry was to create a whole new custom `IRelationalStoreConfiguration` implementation. This PR adds the convenience of providing a custom one to the existing implementation.
> Add support for custom IPrimaryKeyHandlerRegistry

- source/Nevermore/IRelationalStoreConfiguration.cs
- source/Nevermore/Mapping/ITableNameProvider.cs
- source/Nevermore/Mapping/TableNameProvider.cs
- source/Nevermore/Mapping/TableNameResolver.cs
- source/Nevermore/RelationalStoreConfiguration.cs
- source/Nevermore/Util/DataModificationQueryBuilder.cs
This PR introduces the `ITableNameResolver` interface and a default implementation. This default implementation attempts to get the table name from the registered document maps. This is consistent with how they're currently retrieved in `DataModificationQueryBuilder`.
`ITableNameResolver` is currently **only** used in the `RelatedDocument`s feature.
> Add support for a custom table name provider

- source/Nevermore.Tests/RelationalStore/ReadTransactionFixture.cs
- source/Nevermore/Advanced/RelationalTransactionRegistry.cs
- source/Nevermore/IRelationalStoreConfiguration.cs
- source/Nevermore/RelationalStore.cs
- source/Nevermore/RelationalStoreConfiguration.cs
This PR makes it possible to specify a custom `IRelationalTransactionRegistry` via `RelationalStoreConfiguration`.
This PR also makes `RelationalTransactionRegistry.WriteCurrentTransactions` virtual so that you can override Nevermore's implementation to include other useful information.
`ConnectionString` and `MaxPoolSize` are no longer exposed by `RelationalTransactionRegistry` as they're duplicates of information already available via `RelationalStoreConfiguration`.
`RelationalTransactionRegistry` now accepts the max SQL connection pool size via its constructor rather than the entire connection string, as that's all it actually needs.
> Make RelationalTransactionRegistry extensible

- source/Nevermore/Advanced/ReadTransaction.cs
- source/Nevermore/IRelationalStoreConfiguration.cs
- source/Nevermore/RelationalStoreConfiguration.cs
[sc-69597]
Nevermore has a feature which allows concurrent queries to be issued to a transaction without the need for MARS to be enabled within SQL Server. It does this by blocking the execution of queries on a semaphore which causes them to be issued to the database server one-at-a-time.
This feature can cause issues in some situations where one query is executed which depends on a previously issued query, creating a deadlock. Nevermore attempts to detect this situation and throw an exception, but cannot always do so reliably.
Currently this feature is on by default, with no option to disable it.
Add a configuration option `SupportConcurrentExecution` to turn this feature on or off as desired. The default will be on for compatibility.
> Add option to disable concurrency protection

- source/Nevermore.Benchmarks/RelationalTransactionRegistryBenchmark.cs
- source/Nevermore/Advanced/RelationalTransactionRegistry.cs
> Remove ConcurrentDictionary from RelationalTransactionRegistry

- source/Nevermore/Advanced/ReadTransaction.cs
[sc-80865]
Updates `ReadTransaction.Dispose()` to ensure that the SQL connection is disposed, even if the other dispose methods throw an exception.
Addressed https://github.com/OctopusDeploy/Issues/issues/8841
> Ensure the SQL connection is always closed when disposing

- source/Nevermore.Tests/QueryBuilderFixture/QueryBuilderFixture.cs
- source/Nevermore/Advanced/QueryBuilder.cs
When including query hints these cannot be part of a nested query as produced by `ToListWithCountAsyncCte`. This change moves any options set on the query to the end of the generated query.
Previously, the syntax generated was invalid.
An existing unit test for `ToListWithCountAsyncCte` has been updated to include a query hint.
> Move `OPTIONS` to end in `ToListWithCountAsyncCte`

- source/Nevermore.Tests/DeadlockAwareLockFixture.cs
- source/Nevermore/Advanced/DeadlockAwareLock.cs
- source/Nevermore/Advanced/DeadlockAwareLockExtensions.cs
- source/Nevermore/Advanced/ReadTransaction.cs
- source/Nevermore/IRelationalStoreConfiguration.cs
- source/Nevermore/RelationalStoreConfiguration.cs
Currently, there is no clear way to determine if a transaction is attempting to run multiple queries "concurrently".
This PR adds a new `LogOnConcurrentExecution` parameter to the `RelationalStoreConfiguration`, which log warnings when multiple concurrent queries are run in a `ReadTransaction` or `WriteTransaction`.
This PR also removes the `SemaphoreSlim` inheritance of `DeadlockAwareLock`, as it hid the fact that `SemaphoreSlim` extension methods were calling the base implementations instead of the overridden ones.
> Add concurrency warning option for transactions
